### ISSUE TITLE
How the project set other language?

### ISSUE THREAD

**Issue by Ngthoai** [DevipriyaSarkar/OCR-Reader#1]
I want to set other language?

**Comment by DevipriyaSarkar** [comment]
The Text API used in this project can recognize text in a variety of languages ([Link](https://developers.google.com/vision/text-overview)). Looks like providing hints within request's `ImageContext` as a list of `languageHints` would help. Please check out the following links:
- https://cloud.google.com/vision/docs/languages
- https://cloud.google.com/vision/docs/reference/rest/v1/images/annotate#imagecontext
