### ISSUE TITLE
Are those utility files from open source ? 

### ISSUE THREAD

**Issue by makkhay** [DevipriyaSarkar/OCR-Reader#2]
Hello, I see there are tons of utility classes such as OcrDetectorProcessor, Ocrgraphics.java. Are those borrowed from the OCR open source? 

p.s, I was wondering to make a translator app, can I use your code? thanks.

**Comment by DevipriyaSarkar** [comment]
Yes. Those are open sourced utility files from [Google samples](https://github.com/googlesamples/android-vision/tree/master/visionSamples/ocr-reader).
Please go ahead and use it.
For more details, check out [Text Recognition API](https://developers.google.com/vision/text-overview).

**Comment by DevipriyaSarkar** [comment]
Also, this [link](https://cloud.google.com/translate/) might help you with your translation app.

**Comment by makkhay** [comment]
Thanks, will let you know how it comes out. :)
